### ISSUE TITLE
Inconsistencies in data if reference sample is changed

### ISSUE THREAD

**Issue by eclipseo** [webmproject/codec-compare#11]
II was sent to this page:

https://storage.googleapis.com/demos.webmproject.org/webp/cmp/2024_01_25/index.html#ref=AVIF+speed+6&matcher_ssim=off&ploty=encoded_size

We're comparing for the same source image and the same SSIMULACRA2.

With WebP chosen as reference:

| of codec | encoded size | encoded time | decoding time |
| ------------ | ------------------- | -------------------- | -------------------- |
|AVIF speed 6|-29.2%|+457.0%|+170.7%|
|JPEG XL effort 7|-26.4%|+300.3%|+239.5%|
|WebP method 4|-|-|-|

compared to WebP method 4	

With JPEG XL chosen as reference:

| of codec | encoded size | encoded time | decoding time |
| ------------ | ------------------- | -------------------- | -------------------- |
|AVIF speed 6|+1.1%|+51.7%|+16.1%|
|JPEG XL effort 7|-|-|-|
|WebP method 4|+35.8%|-75.0%|-70.5%|

compared to JPEG XL effort 7

With AVIF chosen as reference:

| of codec | encoded size | encoded time | decoding time |
| ------------ | ------------------- | -------------------- | -------------------- |
|AVIF speed 6|-|-|-|
|JPEG XL effort 7|-1.0%|-34.1%|-13.9%|
|WebP method 4|+41.2%|-82.0%|-63.1%|

compared to AVIF speed 6

1. If WebP is the reference, then AVIF is 2.8 percentage point smaller than JPEG XL.
2. If JPEG XL is the reference, then AVIF is 1.1 percentage point bigger than JPEG XL.
3. If AVIF is chosen as the reference, JPEG XL is 1.0 percentage point smaller than AVIF.

So, 2. and 3. are relatively consistent with each other, but 1. is not.

What can explain this inconsistency? Data points are not from the same source if we change reference point?

**Comment by y-guyon** [comment]
Hi Robert-André, thank you for your interest in Codec-Compare and for your work on the framework that was used for previous comparisons.

> What can explain this inconsistency?

In the Codec-Compare interface, I was careful not to imply anything more than what the filtered data points show. So the interface only shows:  
1. If WebP is the reference, then AVIF is ~2.8 percentage point smaller than JPEG XL~ **1.41 times smaller than WebP**.
2. If JPEG XL is the reference, then AVIF is 1.1 percentage point bigger than JPEG XL.
3. If AVIF is chosen as the reference, JPEG XL is 1.0 percentage point smaller than AVIF.

> Data points are not from the same source if we change reference point?

The matched AVIF/WebP data points and the matched JPEG XL/WebP data points are not the same set in 1. Comparing codecs based on that can be inconsistent.

Since that was misleading, I uploaded default presets with only two codecs in the [latest batch](https://storage.googleapis.com/demos.webmproject.org/webp/cmp/2024_03_25/index.html) (except in the "All codecs at all efforts" preset which is convenient to experts). This way no one is tempted to compare apples with oranges.

An alternative would be to filter out the data points that are not used by all codecs but this often ends up in too few data points to get meaningful results.

**Comment by eclipseo** [comment]
Oh ok my bad, I misread the data then!

Sidenote, On https://storage.googleapis.com/demos.webmproject.org/webp/cmp/2024_03_25/index.html, it says it is version 0.2.2, are the sources available for it too?

Thanks a lot for your great tool!

**Comment by y-guyon** [comment]
> version 0.2.2, are the sources available for it too?

Yes: https://github.com/webmproject/codec-compare/pull/9  
I just did not create a release for that version as the changes were minor.
