### ISSUE TITLE
Backend sample

### ISSUE THREAD

**Issue by nucliweb** [webmproject/codec-compare#5]
Hi!

Great project 👏 

Do you have a backend sample to encode different image formats and qualities, and then generate the JSON file?

**Comment by y-guyon** [comment]
Thank you for your question and interest in Codec-Compare.

I use a custom image encoding/decoding framework that I did not have the time to release publicly yet.

In the meantime, please find a bash script on the wiki:  
https://github.com/webmproject/codec-compare/wiki/Generate-AVIF,-WebP,-JPEG-XL-data-(bash-script)

**Comment by nucliweb** [comment]
Sorry, the problem is running the command:

```bash
cmake -S . -B build \
      -DBUILD_TESTING=OFF -DJPEGXL_ENABLE_BENCHMARK=OFF -DJPEGXL_ENABLE_EXAMPLES=OFF \
      -DJPEGXL_ENABLE_JPEGLI=OFF -DJPEGXL_ENABLE_OPENEXR=OFF -DJPEGXL_ENABLE_DEVTOOLS=ON \
      -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
```

## Error

![image](https://github.com/webmproject/codec-compare/assets/1307927/d2619bea-61e9-4407-a3c8-bec2917cb827)

### line 100 of `CMakeList.txt`

![image](https://github.com/webmproject/codec-compare/assets/1307927/7c3d5ff7-981d-4d35-987c-29bcb7fc400a)

### Running `./deps.sh`

![image](https://github.com/webmproject/codec-compare/assets/1307927/366a0cd6-9d22-4a46-9b9f-d4582d43f98e)


Then, I tried to run `./deps.sh` [step by step](https://github.com/libjxl/libjxl/blob/main/deps.sh#L82-L91).

**Comment by y-guyon** [comment]
If I understand correctly, `libjxl/deps.sh` does not report any issue but `cmake -S libjxl` complains that a dependency is missing.

Two things I would try:
- Run from a path without any white space in it (I see a folder named "Tile images samples"). This is a common source of problems.
- Use the `cmake` flag `-DJPEGXL_ENABLE_SKCMS=OFF`. I do not know what is the purpose of the skia dependency. Maybe it is required.

No matter the root cause, it seems to be an issue with libjxl and I suggest you file an issue [there](https://github.com/libjxl/libjxl/issues).

**Comment by y-guyon** [comment]
The image codec benchmark framework Codec-Compare-Gen is now available:
https://github.com/webmproject/codec-compare-gen
